global using RouteIt.ViewModels;
global using RouteIt.Models;
global using CommunityToolkit.Mvvm.ComponentModel;
global using CommunityToolkit.Mvvm.Input;
global using System.Diagnostics;
global using Mapsui;
global using Mapsui.Projections;
global using Mapsui.UI.Maui;
global using System.Text.Json;
global using Location = Microsoft.Maui.Devices.Sensors.Location;
